name: Music API CD by Django

on:
  push:
    branches: [master]

jobs:
  test:
    services:
      postgres:
        image: postgres:13
        ports:
          -5432: 5432

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-checkout@v2
        with:
          python-version: 3.9
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Run tests
        run:
          pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: whoami
